# Generated by Django 5.0 on 2023-12-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0002_family_remove_produit_famille_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_panier', models.CharField(default='DEFAULT_CODE_PANIER', max_length=100)),
                ('label', models.CharField(default='DEFAULT_LABEL', max_length=100)),
                ('description', models.TextField(default='DEFAULT_DESCRIPTION')),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='code_name',
            field=models.CharField(default='DEFAULT_CODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='DEFAULT_DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=100),
        ),
        migrations.CreateModel(
            name='Ponderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderation', models.FloatField(default=0.0)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.product')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='products',
            field=models.ManyToManyField(through='gestion_produits.Ponderation', to='gestion_produits.product'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='DEFAULT_ZONE', max_length=100)),
                ('gps', models.CharField(default='DEFAULT_GPS', max_length=100)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.price')),
            ],
        ),
    ]
