# Generated by Django 5.0 on 2023-12-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0003_panier_remove_family_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointdevente',
            name='price',
        ),
    ]
