# Generated by Django 5.0 on 2023-12-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0004_remove_pointdevente_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointDeVente',
            new_name='pointvente',
        ),
    ]
