# Generated by Django 5.0 on 2023-12-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0005_rename_pointdevente_pointvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='zone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.pointvente'),
            preserve_default=False,
        ),
    ]
