# Generated by Django 5.0 on 2023-12-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0006_price_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ponderation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.ponderation'),
        ),
    ]
