# Generated by Django 5.0 on 2023-12-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0007_price_ponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
