# Generated by Django 5.0 on 2023-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0008_family_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvente',
            name='mougataa',
            field=models.CharField(default='DEFAULT_MOUGATAA    ', max_length=100),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='wilaya',
            field=models.CharField(default='DEFAULT_WILAYA', max_length=100),
        ),
    ]
